name: CI/CD

on:
  push:
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
  steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - run: echo "Always success"
